# Generated by Django 6.0.5 on 2026-05-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_remove_movie_poster_url_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Now Showing', 'Now Showing'), ('Coming Soon', 'Coming Soon')], default='Now Showing', max_length=20),
        ),
    ]
