# Generated by Django 6.0.5 on 2026-05-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_movie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
