# Generated by Django 6.0.5 on 2026-09-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day'), ('Night', 'Night')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
