# Generated by Django 6.0.5 on 2026-09-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_loyaltytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loyalty_points',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
    ]
